# Generated by Django 5.2.17 on 2026-08-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_permissions_accesstemplate',
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'form_permissions_formdefinition',
            },
        ),
        migrations.CreateModel(
            name='FormFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='form_permissions.formdefinition')),
            ],
            options={
                'db_table': 'form_permissions_formfieldgroup',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('field_type', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_permissions.formdefinition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='form_permissions.formfieldgroup')),
            ],
            options={
                'db_table': 'form_permissions_formfield',
                'unique_together': {('form', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RoleFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('hidden', 'Hidden'), ('read', 'Read'), ('write', 'Write'), ('read_write', 'Read/Write')], default='hidden', max_length=20)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_permissions.formfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_accesses', to='form_permissions.formdefinition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_permissions.formfieldgroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_accesses', to='accounts.role')),
            ],
            options={
                'db_table': 'form_permissions_rolefieldaccess',
                'unique_together': {('role', 'form', 'group', 'field')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('hidden', 'Hidden'), ('read', 'Read'), ('write', 'Write'), ('read_write', 'Read/Write')], default='hidden', max_length=20)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_permissions.formfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_permissions.formdefinition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_permissions.formfieldgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_permissions.accesstemplate')),
            ],
            options={
                'db_table': 'form_permissions_templatefieldaccess',
                'unique_together': {('template', 'form', 'group', 'field')},
            },
        ),
    ]
