# Generated by Django 5.2.17 on 2026-08-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retained_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retained_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledgers', to='partners.partner')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger', to='billing.paymenttransaction')),
            ],
            options={
                'db_table': 'commission_ledger',
                'unique_together': {('transaction', 'partner')},
            },
        ),
    ]
