# Generated by Django 5.2.17 on 2026-08-23 09:25

import billing.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('partners', '0002_division_area_bank_account_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.district'),
        ),
        migrations.AddField(
            model_name='client',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.division'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='clients/images/', validators=[billing.validators.validate_file_size, billing.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nid_scan',
            field=models.FileField(blank=True, null=True, upload_to='clients/nid/', validators=[billing.validators.validate_file_size, billing.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='client',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.union'),
        ),
        migrations.AddField(
            model_name='client',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.upazila'),
        ),
    ]
