# Generated by Django 5.2.17 on 2026-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('internet', 'Internet'), ('voice', 'Voice'), ('combo', 'Combo'), ('enterprise', 'Enterprise')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed', models.CharField(blank=True, max_length=100)),
                ('validity_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packages_package',
                'ordering': ['-created_at'],
            },
        ),
    ]
